api-key: abc123

cookies: 'cookies.txt'

rate-limit: 512K

dont-sleep: ''

download-folder: 'C:\YouTube Downloads'

output-template: '%(uploader)s_%(title)s_%(id)s'

playlists:
  - PL207194C1FE5DC72B
  - PLD3FC61763E88EDD9